AllCops:
  TargetRubyVersion: 2.6
  # Include:
    # - '**/Rakefile'
    # - '**/config.ru'
  Exclude:
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

# 日本語でコメントできるようにします
Style/AsciiComments:
  Enabled: false

# frozen commentは必須ではありません
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメントに関するチェックをしません
Style/Documentation:
  Enabled: false

# ifの条件内などで変数への代入を許可
Lint/AssignmentInCondition:
  Enabled: false

Rails/InverseOf:
  Enabled: false
